language: php
sudo: false
before_install:
  - docker run -d --rm -p 127.0.0.1:6379:6379 redis:${REDIS_VERSION:=3}
before_script:
  - composer install --no-interaction
script:
  - vendor/bin/phpunit tests
matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
